### ISSUE TITLE
Feature request: get specific matrix value

### ISSUE THREAD

**Issue by ruudalberts** [kongondo/FieldtypeMatrix#22]
Hi kongondo,

As requested here: https://processwire.com/talk/topic/8581-module-matrix-fieldtype-inputfield/?p=104245

Would it be possible to pick a specific value from the matrix?
So on a certain page, I would like to spit out the value at row 2, column C, without having to loop the whole pricetable to find that specific value.

Thanks!

**Comment by kongondo** [comment]
Apologies! This already works. See the examples in my post [here](https://processwire.com/talk/topic/8581-module-matrix-fieldtype-inputfield/?p=104743)
