### ISSUE TITLE
Options to ignore first row and first column when importing CSV

### ISSUE THREAD

**Issue by adrianbj** [kongondo/FieldtypeMatrix#23]
I think this is important when the user is trying to import data from a CSV. The first row can be dealt with easily, but the first column is more complicated and would typically require editing the CSV in Excel first to remove that first column.

This option would also make it possible to import data that was exported from a Matrix field since it includes these.

Thanks!

**Comment by kongondo** [comment]
Done. Implemented in Dev version 1.0.4.
